### ISSUE TITLE
Fix listing of PiE staff, high schools, and possibly sponsor logos

### ISSUE THREAD

**Issue by tobinsarah** [pioneers/website#74] opened 2016-02-05 04:41 UTC
The current layout on "The PiE Team" page, and the high school list on "Robotics competition", has multiple problems:

* The text is left justified while the images are centered. This makes the page unbalanced-looking and hard to read. I didn't notice the text the first time I visited the page, and its not visually clear which image the text corresponds to. (I mean, I can figure it out from context b/c I know Tommy is in the first image not the second, but if I didn't know that I would be confused!)

* Since its vertical, it leaves a lot of white space and makes the page feel unnecessarily long. Perhaps make two columns?
  * Same comment for the gallery and perhaps list of sponsors. Sponsors actually look okay right now since the logos are longer horizontally, but I think its worth a try to see if there's a more compact way to display the logos, if its not too much effort to try out new layouts.

**Comment by tobinsarah** [comment] 2016-02-05 05:20
I'm looking at the website on my phone now, and these vertical lists make a lot more sense! Still would be if they looked better on a computer, though.

**Comment by cwang395** [comment] 2016-02-06 21:22
What web browser are you using?

**Comment by tobinsarah** [comment] 2016-02-07 05:38
I'm trying both Chrome Version 47.0.2526.106 and Safari Version 6.2.3 (8537.85.12.18).

**Comment by cwang395** [comment] 2016-02-08 05:08
Duplicate of #73

**Closed by cwang395** 2016-02-08 05:08 UTC
Labels: bug, duplicate, help wanted
